title: King's Cross Publishing
email: support@kingscrosspublishing.com
baseurl: ""
url: "http://kingscrosspublishing.com/"

sass:
  sass_dir: _sass
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME

host: 0.0.0.0
port: 4000
